apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-tracker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-tracker
  template:
    metadata:
      labels:
        app: text-tracker
    spec:
      containers:
        - name: web
          image: nutanpasham/text-tracker-web:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: repo-volume
              mountPath: /repo
          envFrom:
            - secretRef:
                name: db-secret   # ğŸ” Inject secrets into web container

        - name: sidecar
          image: nutanpasham/text-tracker-sidecar:latest
          volumeMounts:
            - name: repo-volume
              mountPath: /repo
          envFrom:
            - secretRef:
                name: db-secret   # ğŸ” Inject secrets into sidecar container

      volumes:
        - name: repo-volume
          emptyDir: {}
